const data =[
    {
    "date": "2019-01-21",
    "explanation": "This is what NASA's Insight lander looks like on Mars. With its solar panels, InSight is about the size of a small bus.  Insight successfully landed on Mars in November with a main objective to detect seismic activity. The featured selfie is a compilation of several images taken of different parts of the InSight lander, by the lander's arm, at different times. SEIS, the orange-domed seismometer seen near the image center last month, has now been placed on the Martian surface.  With this selfie, Mars InSight continues  a long tradition of robotic spacecraft on Mars taking and returning images of themselves, including Viking, Sojourner, Pathfinder, Spirit, Opportunity, Phoenix, and Curiosity.  Data taken by Mars Insight is expected to give humanity unprecedented data involving the interior of Mars, a region thought to harbor formation clues not only about Mars, but Earth.    Growing Gallery:  Last Night's Total Lunar Eclipse",
    "hdurl": "https://apod.nasa.gov/apod/image/1901/Selfie_InSight_4391.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "InSight Lander Takes Selfie on Mars",
    "url": "https://apod.nasa.gov/apod/image/1901/Selfie_InSight_1080.jpg",
    "likes": "0"
    },
    {
    "copyright": "Tunç Tezel",
    "date": "2010-07-10",
    "explanation": "Four bright celestial beacons and a faint triangle of light follow the plane of the ecliptic as it arcs high through this southern hemisphere night skyscape. Seen on a July winter night from Lake Taupo on New Zealand's North Island, the line-up features Venus, Regulus (alpha star of Leo), Mars, and Saturn from lower left to upper right. Just put your cursor over the picture to identify the planets and constellations. The delicate luminous glow of Zodiacal Light, sunlight scattered by dust along the ecliptic, also rises above the horizon from the lower left. Of course, defined by the path of the Sun through planet Earth's sky, the ecliptic plane rides low during July nights in the northern hemisphere's summer skies. Tomorrow, the Moon and Sun will meet on the ecliptic. Along a track across the southern Pacific Ocean, the daytime sky will feature a total solar eclipse.  Total Solar Eclipse: Times and Visibility | Webcast",
    "hdurl": "https://apod.nasa.gov/apod/image/1007/TaupoPlanets_tezel.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Ecliptic New Zealand",
    "url": "https://apod.nasa.gov/apod/image/1007/TaupoPlanets_tezel900h.jpg",
    "likes": "0"
    },
    {
    "date": "2022-09-05",
    "explanation": "Stars created these cliffs. Specifically, the destructive winds and energetic light from the stars in the open cluster NGC 3324 eroded away part of a mountain of dark interstellar dust in the northern part of the Carina Nebula. Several of these stars are visible toward the top of this highly detailed image taken recently by the James Webb Space Telescope, the largest astronomical telescope ever launched. Webb's large mirror and ability to see dust-piercing infrared light has enabled it to capture fascinating details in the dust, hundreds of previously hidden stars, and even some galaxies far in the distance.  The featured jagged cliffs occur in part of Carina known as the Gabriela Mistral Nebula -- because when viewed in another orientation, they appear similar to the facial profile of the famous Chilean poet.  These nebular cliffs occur about 7,600 light years away toward the southern constellation of Carina.   Astrophysicists: Browse 2,800+ codes in the Astrophysics Source Code Library",
    "hdurl": "https://apod.nasa.gov/apod/image/2209/CarinaCliffs_Webb_2000.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Carina Cliffs from the Webb Space Telescope",
    "url": "https://apod.nasa.gov/apod/image/2209/CarinaCliffs_Webb_1080.jpg",
    "likes": "0"
    },
    {
    "date": "2000-05-22",
    "explanation": "Bridges the length of a planet can form on the Sun in a matter of hours.  Known as light bridges, these structures may form as large sunspot groups decay.  Above, one of the sharpest photographs of the Sun ever taken shows two such light bridges that appeared late last month.  The 5000-kilometer long bridges connect moderately dark penumbral regions across the cool abyss of two dark sunspot umbras.  A movie shows that material tends more to rise from below and fall rather than to cross the light bridges.  Bright bubbling granules surround the sunspot group.  The impressive details on this recently released picture from the Swedish Solar Vacuum Telescope were made possible by new adaptive optics that correct for the blurring of the Earth's atmosphere.  What eventually became of the light bridges?  As days progressed, the bridge region expanded to fill the void as the sunspots moved apart and decayed.",
    "hdurl": "https://apod.nasa.gov/apod/image/0005/lightbridges_svst_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Light Bridges on the Sun",
    "url": "https://apod.nasa.gov/apod/image/0005/lightbridges_svst.jpg",
    "likes": "0"
    },
    {
    "copyright": "Bray Falls",
    "date": "2021-05-14",
    "explanation": "A gorgeous spiral galaxy, M104 is famous for its nearly edge-on profile featuring a broad ring of obscuring dust lanes. Seen in silhouette against an extensive central bulge of stars, the swath of cosmic dust lends a broad brimmed hat-like appearance to the galaxy suggesting a more popular moniker, the Sombrero Galaxy. This sharp optical view of the well-known galaxy made from ground-based image data was processed to preserve details often lost in overwhelming glare of M104's bright central bulge. Also known as NGC 4594, the Sombrero galaxy can be seen across the spectrum, and is host to a central supermassive black hole. About 50,000 light-years across and 28 million light-years away, M104 is one of the largest galaxies at the southern edge of the Virgo Galaxy Cluster. Still the colorful spiky foreground stars in this field of view lie well within our own Milky Way galaxy.",
    "hdurl": "https://apod.nasa.gov/apod/image/2105/m104apodsub.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "M104: The Sombrero Galaxy",
    "url": "https://apod.nasa.gov/apod/image/2105/m104apodsub800c.jpg",
    "likes": "0"
    },
    {
    "date": "2020-05-19",
    "explanation": "Would you like a NASA astronomy-exploration poster?  You are just one page-print away. Any of the panels you see on the featured image can appear on your wall.  Moreover, this NASA page has, typically, several more posters of each of the Solar System objects depicted.  These posters highlight many of the places humanity, through NASA, has explored in the past 50 years, including our Sun, and planets Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune. Moons of Jupiter that have been posterized include Europa, Ganymede, Callisto, and Io, while moons of Saturn that can be framed include Enceladus and Titan.  Images of Pluto, Ceres, comets and asteroids are also presented, while six deep space scenes -- well beyond our Solar System -- can also be prominently displayed.  If you lack wall space or blank poster sheets don't despair -- you can still print many of these out as trading cards.",
    "hdurl": "https://apod.nasa.gov/apod/image/2005/SolarSystemPosters_NASA_2130.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Posters of the Solar System",
    "url": "https://apod.nasa.gov/apod/image/2005/SolarSystemPosters_NASA_1080.jpg",
    "likes": "0"
    },
    {
    "date": "2014-03-18",
    "explanation": "Did the universe undergo an early epoch of extremely rapid expansion? Such an inflationary epoch has been postulated to explain several puzzling cosmic attributes such as why our universe looks similar in opposite directions. Yesterday, results were released showing an expected signal of unexpected strength, bolstering a prediction of inflation that specific patterns of polarization should exist in cosmic microwave background radiation -- light emitted 13.8 billion years ago as the universe first became transparent. Called B-mode polarizations, these early swirling patterns can be directly attributed to squeeze and stretch effects that gravitational radiation has on photon-emitting electrons. The surprising results were discovered in data from the Background Imaging of Cosmic Extragalactic Polarization 2 (BICEP2) microwave observatory near the South Pole. BICEP2 is the building-mounted dish pictured above on the left. Note how the black polarization vectors appear to swirl around the colored temperature peaks on the inset microwave sky map. Although statistically compelling, the conclusions will likely remain controversial while confirmation attempts are made with independent observations.",
    "hdurl": "https://apod.nasa.gov/apod/image/1403/DSLmap_BICEP2_3888.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Cosmic Microwave Map Swirls Indicate Inflation",
    "url": "https://apod.nasa.gov/apod/image/1403/DSLmap_BICEP2_960.jpg",
    "likes": "0"
    },
    {
    "copyright": "Axel\nMellinger",
    "date": "2009-08-22",
    "explanation": "Named for Australian astronomer Colin Stanley Gum (1924-1960), The Gum Nebula is so large and close it is actually hard to see. In fact, we are only about 450 light-years from the front edge and 1,500 light-years from the back edge of this cosmic cloud of glowing hydrogen gas. Covered in this 41 degree-wide mosaic of H-alpha images, the faint emission region is otherwise easy to lose against the background of Milky Way stars. The complex nebula is thought to be a supernova remnant over a million years old, sprawling across the southern constellations Vela and Puppis.  Sliding your cursor over this spectacular wide field view will reveal the location of objects embedded in The Gum Nebula, including the Vela supernova remnant.   digg_url ='http://apod.nasa.gov/apod/ap090822.html'; digg_skin = 'compact';",
    "hdurl": "https://apod.nasa.gov/apod/image/0908/Vela_50mm_HaRGB_1000.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The Gum Nebula",
    "url": "https://apod.nasa.gov/apod/image/0908/Vela_50mm_HaRGB_f88.jpg",
    "likes": "0"
    },
    {
    "copyright": "Polar Image",
    "date": "2002-11-10",
    "explanation": "Many think it is just a myth.  Others think it is true but its cause isn't known.  Adventurers pride themselves on having seen it.  It's a green flash from the Sun.  The truth is the green flash does exist and its cause is well understood.  Just as the setting Sun disappears completely from view, a last glimmer appears startlingly green.  The effect is typically visible only from locations with a low, distant horizon, and lasts just a few seconds. A green flash is also visible for a rising Sun, but takes better timing to spot.  A dramatic green flash was caught in the above photograph in 1992 from Finland. The Sun itself does not turn partly green, the effect is caused by layers of the Earth's atmosphere acting like a prism.",
    "hdurl": "https://apod.nasa.gov/apod/image/0211/greenflash_parviainen_big.gif",
    "media_type": "image",
    "service_version": "v1",
    "title": "A Green Flash from the Sun",
    "url": "https://apod.nasa.gov/apod/image/0211/greenflash_parviainen.jpg",
    "likes": "0"
    },
    {
    "copyright": "Tim Carruthers",
    "date": "2010-03-13",
    "explanation": "Only 11 million light-years away, Centaurus A is the closest active galaxy to planet Earth. Spanning over 60,000 light-years, the peculiar elliptical galaxy, also known as NGC 5128, is featured in this sharp color image. Centaurus A is apparently the result of a collision of two otherwise normal galaxies resulting in a fantastic jumble of star clusters and imposing dark dust lanes. Near the galaxy's center, left over cosmic debris is steadily being consumed by a central black hole with a billion times the mass of the Sun. As in other active galaxies, that process likely generates the radio, X-ray, and gamma-ray energy radiated by Centaurus A.",
    "hdurl": "https://apod.nasa.gov/apod/image/1003/centaurusA_carruthers.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Centaurus A",
    "url": "https://apod.nasa.gov/apod/image/1003/centaurusA_carruthers_c900.jpg",
    "likes": "0"
    },
    {
    "date": "2010-09-05",
    "explanation": "In the center of a swirling whirlpool of hot gas is likely a beast that has never been seen directly: a black hole.  Studies of the bright light emitted by the swirling gas frequently indicate not only that a black hole is present, but also likely attributes.  The gas surrounding GRO J1655-40, for example, has been found to display an unusual flickering at a rate of 450 times a second.  Given a previous mass estimate for the central object of seven times the mass of our Sun, the rate of the fast flickering can be explained by a black hole that is rotating very rapidly.  What physical mechanisms actually cause the flickering -- and a slower quasi-periodic oscillation (QPO) -- in accretion disks surrounding black holes and neutron stars remains a topic of much research.",
    "hdurl": "https://apod.nasa.gov/apod/image/0904/blackhole_hobart_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "GRO J1655-40: Evidence for a Spinning Black Hole",
    "url": "https://apod.nasa.gov/apod/image/0904/blackhole_hobart.jpg",
    "likes": "0"
    },
    {
    "copyright": "Robert Fedez",
    "date": "2021-08-31",
    "explanation": "The Moon is normally seen in subtle shades of grey or gold.  But small, measurable color differences have been greatly exaggerated to make this telescopic, multicolored, moonscape captured during the Moon's full phase.  The different colors are recognized to correspond to real differences in the chemical makeup of the lunar surface.  Blue hues reveal titanium rich areas while orange and purple colors show regions relatively poor in titanium and iron.  The familiar Sea of Tranquility, or Mare Tranquillitatis, is the blue area toward the upper right.  White lines radiate across the orange-hued southern lunar highlands from 85-kilometer wide ray-crater Tycho at bottom right.  The full moon that occurred earlier this month could be counted as a seasonal blue moon because it was, unusually, the third of four full moons to occur during northern summer (and hence southern winter).  The featured 272-image composite demonstrates that the full Moon is always blue, but usually not blue enough in hue to ooh.   Almost Hyperspace: Random APOD Generator",
    "hdurl": "https://apod.nasa.gov/apod/image/2108/Luna_Fedez_1600.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "A Blue Moon in Exaggerated Colors",
    "url": "https://apod.nasa.gov/apod/image/2108/Luna_Fedez_960.jpg",
    "likes": "0"
    },
    {
    "date": "2018-11-27",
    "explanation": "Welcome to Mars, NASA Insight.  Yesterday NASA's robotic spacecraft InSight made a dramatic landing on Mars after a six-month trek across the inner Solar System. Needing to brake from 20,000 km per hour to zero in about seven minutes, Insight decelerated by as much as 8  g's and heated up to 1500 degrees Celsius as it deployed a heat shield, a parachute, and at the end, rockets.  The featured image was the first taken by InSight on Mars, and welcome proof that the spacecraft had shed enough speed to land softly and function on the red planet. During its final descent, InSight's rockets kicked up dust which can be seen stuck to the lens cap of the Instrument Context Camera. Past the spotty dirt, parts of the lander that are visible include cover bolts at the bottom and a lander footpad on the lower right. Small rocks are visible across the rusty red soil, while the arc across the top of the image is the Martian horizon dividing land and sky. Over the next few weeks InSight will deploy several scientific instruments, including a rumble-detecting seismometer.  These instruments are expected to give humanity unprecedented data involving the interior of Mars, a region thought to harbor formation clues not only about Mars, but Earth.",
    "hdurl": "https://apod.nasa.gov/apod/image/1811/FirstLight_InSight_1024_annotated.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "InSight's First Image from Mars",
    "url": "https://apod.nasa.gov/apod/image/1811/FirstLight_InSight_1024_annotated.jpg",
    "likes": "0"
    },
    {
    "date": "2004-12-15",
    "explanation": "Pictured above, the path of the robot rover Spirit on Mars can be traced far into the distance.  Spirit has now crossed kilometers of plains covered with rocks and sand, approached the lip of a crater 200-meters across, and climbed a series of hills.  Spirit's path has been not only one of adventure but discovery.  Landing inside vast Gusev crater near the beginning of this year, Spirit, along with its sister robot Opportunity across the planet, has uncovered key evidence for ancient Martian water.  The recent discovery of goethite, a mineral only known to form on Earth in the presence of water, bolsters the case.  Spirit and Opportunity continue to roam the red planet in search of different and more detailed clues to the unfolding ancient past of Mars.",
    "hdurl": "https://apod.nasa.gov/apod/image/0412/path_spirit_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Looking Back Over Mars",
    "url": "https://apod.nasa.gov/apod/image/0412/path_spirit.jpg",
    "likes": "0"
    },
    {
    "copyright": "Nigel Sharp",
    "date": "2003-07-13",
    "explanation": "One of the most identifiable nebulae in the sky, the Horsehead Nebula in Orion, is part of a large, dark,  molecular cloud.  Also known as Barnard 33, the unusual shape was first discovered on a photographic plate in the late 1800s.  The red glow originates from hydrogen gas predominantly behind the nebula, ionized by the nearby bright star Sigma Orionis.  The darkness of the Horsehead is caused mostly by thick dust, although the lower part of the Horsehead's neck casts a shadow to the left.  Streams of gas leaving the nebula are funneled by a strong magnetic field.  Bright spots in the Horsehead Nebula's base are young stars just in the process of forming.  Light takes about 1500 years to reach us from the Horsehead Nebula.   The above image was taken with the 0.9-meter telescope at  Kitt Peak National Observatory.",
    "hdurl": "https://apod.nasa.gov/apod/image/0112/horsehead_noao_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The Horsehead Nebula",
    "url": "https://apod.nasa.gov/apod/image/0112/horsehead_noao.jpg",
    "likes": "0"
    },
    {
    "copyright": "Boris DmitrievNight Scape",
    "date": "2014-12-30",
    "explanation": "The awesomeness in this image comes in layers. The closest layer, in the foreground, contains the Peak Terskol Observatory located in the northern Caucasus Mountains of Russia.  The white dome over the 2-meter telescope is clearly visible.  The observatory is located on a shoulder of Mt. Elbrus, the highest mountain in Europe, with other peaks visible in a nearby background layer.  Clouds are visible both in front of and behind the mountain peaks. The featured three-image composite panorama was taken in 2014 August. Far in the distance is the most distant layer: the stars and nebulas of the night sky, with the central band of the Milky Way rising on the image right.",
    "hdurl": "https://apod.nasa.gov/apod/image/1412/ObsMntsUni_dmitriev_1280.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Observatory, Mountains, Universe",
    "url": "https://apod.nasa.gov/apod/image/1412/ObsMntsUni_dmitriev_960.jpg",
    "likes": "0"
    },
    {
    "date": "2012-04-28",
    "explanation": "Last Sunday's bright fireball meteor falling through skies over California and Nevada produced sonic booms over a broad area around 7:51 am. Estimates indicate the meteor was about the size of a minivan. Astronomer Peter Jenniskens subsequently recovered these fragments of a crushed 4 gram meteorite, the second find from this meteor fall, in the parking lot of the Henningsen-Lotus state park, not far from Sutter's Mill. This is now known as the Sutter's Mill Meteorite, the location famous for its association with the California Gold Rush. The meteorite may well be astronomer's gold too, thought to be a rare CM type carbonaceous chondrite, a type rich in organic compounds and similar to the Murchison Meteorite. To trace the meteor's orbit, details of its breakup, and aid in locating more fragements, scientists are also searching for video records. Security cameras across a wide area could have accidently captured the fireball event near 7:51 am PDT on April 22; e.g. California (SF Bay Area, Los Angeles, near Redding) and Nevada (Reno area, Tonopah), even in southern parts of Oregon and near Salt Lake City in Utah. If you have video footage of the event, please use the contact information here.",
    "hdurl": "https://apod.nasa.gov/apod/image/1204/ACD12-0067-001jenniskens.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Sutter's Mill Meteorite",
    "url": "https://apod.nasa.gov/apod/image/1204/ACD12-0067-001jenniskens900.jpg",
    "likes": "0"
    },
    {
    "date": "2016-06-04",
    "explanation": "Fifty years ago, Surveyor 1 reached the Moon. Launched on May 30, 1966 and landed on June 2, 1966 with the Moon at full phase it became the first US spacecraft to make a soft landing on another world. The first of seven Surveyor missions intended to test the lunar terrain for the planned Apollo landings it sent back over 10,000 images before lunar nightfall on June 14. The total rose to over 11,000 images returned before its second lunar night began on July 13. Surveyor 1 continued to respond from the lunar surface until January 7, 1967.  Captured in this 2009 image from the Lunar Reconnaissance Orbiter, the first Surveyor still stands at its landing site, a speck in the Oceanus Procellarum (the Ocean of Storms). With the Sun low on the western horizon the lonely, 3.3 meter tall spacecraft casts a shadow almost 15 meters long in the late lunar afternoon.",
    "hdurl": "https://apod.nasa.gov/apod/image/1606/surv1_lro_thumb.png",
    "media_type": "image",
    "service_version": "v1",
    "title": "The Shadow of Surveyor 1",
    "url": "https://apod.nasa.gov/apod/image/1606/surv1_lro_thumbcrop.jpg",
    "likes": "0"
    },
    {
    "copyright": "John Kraus",
    "date": "2021-02-22",
    "explanation": "What's that on either side of the Moon? Starships. Specifically, they are launch-and-return reusable rockets being developed by SpaceX to lift cargo and eventually humans from the Earth's surface into space.  The two rockets pictured are SN9 (Serial Number 9) and SN10 which were captured near their Boca Chica, Texas launchpad last month posing below January's full Wolf Moon. The Starships house liquid-methane engines inside rugged stainless-steel shells. SN9 was test-launched earlier this month and did well with the exception of one internal rocket that failed to relight during powered descent.  SN10 continues to undergo ground tests and may be test-launched later this month.",
    "hdurl": "https://apod.nasa.gov/apod/image/2102/StarshipsMoon_Kraus_2048.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Moon Rising Between Starships",
    "url": "https://apod.nasa.gov/apod/image/2102/StarshipsMoon_Kraus_1080.jpg",
    "likes": "0"
    },
    {
    "date": "2004-09-24",
    "explanation": "Reminiscent of popular images of the lovely Pleiades star cluster that lies within our own Milky Way Galaxy, this false-color x-ray view actually explores the center of a much more extended cosmic family -- the Fornax cluster of galaxies some 65 million light-years away. Spanning nearly 900,000 light-years, the Chandra Observatory composite image reveals high-energy emission from several giant galaxies near the Fornax cluster center and an immense, diffuse cloud of x-ray emitting hot gas. On the whole, the hot cluster gas seems to be trailing toward the upper left in this view. As a result, astronomers surmise that the Fornax cluster core is moving toward the lower right, encountering an intergalactic headwind as it sweeps through a larger, less dense cloud of material. In fact, along with another visible galaxy grouping at the outskirts of the cluster, the Fornax cluster core galaxies seem to be moving toward a common point, attracted by the dominating gravity of unseen structures of dark matter in the region.",
    "hdurl": "https://apod.nasa.gov/apod/image/0409/fornax_cxc_full.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Fornax Cluster in Motion",
    "url": "https://apod.nasa.gov/apod/image/0409/fornax_cxc_c1.jpg",
    "likes": "0"
    },
    {
    "copyright": "Adam Block",
    "date": "2013-12-26",
    "explanation": "Gorgeous spiral galaxy M33 seems to have more than its fair share of glowing hydrogen gas. A prominent member of the local group of galaxies, M33 is also known as the Triangulum Galaxy and lies about 3 million light-years distant.  Its inner 30,000 light-years are shown in this telescopic galaxy portrait that enhances the reddish ionized hydrogen clouds or HII regions. Sprawling along loose spiral arms that wind toward the core, M33's giant HII regions are some of the largest known stellar nurseries, sites of the formation of short-lived but very massive stars. Intense ultraviolet radiation from the luminous, massive stars ionizes the surrounding hydrogen gas and ultimately produces the characteristic red glow. To enhance this image, broadband data was used to produce a color view of the galaxy and combined with narrowband data recorded through a hydrogen-alpha filter, transmitting the light of the strongest hydrogen emission line. To see the monochromatic narrowband data alone, move your cursor over the image, or take this video tour of the hydrogen clouds of M33.",
    "hdurl": "https://apod.nasa.gov/apod/image/1312/M33block_Ha_enhanced.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The Hydrogen Clouds of M33",
    "url": "https://apod.nasa.gov/apod/image/1312/M33block_Ha_enhanced900.jpg",
    "likes": "0"
    },
    {
    "date": "1997-02-18",
    "explanation": "Callisto's surface\r is not without fault. In fact, an explorer crossing the surface\r of this large moon of Jupiter\r would need climbing equipment to pass this large, recently discovered\r fault. The above picture\r was released last week and was taken in November 1996 by the robot spacecraft Galileo\r currently orbiting Jupiter.\r As the Sun illuminates Callisto's\r surface from the left, the unusual cliff or scarp\r stands out by the shadow it casts to the right. This cliff and\r others were probably formed when a large object collided with\r Callisto\r early in its history. Of the many visible craters\r in the above photograph, the smallest visible is about a football\r field across, while the largest is more than a kilometer.\r",
    "hdurl": "https://apod.nasa.gov/apod/image/9702/callistoscarp_gal_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "A Big Cliff on Jupiter's Callisto\r\nCredit:",
    "url": "https://apod.nasa.gov/apod/image/9702/callistoscarp_gal.jpg",
    "likes": "0"
    },
    {
    "date": "2013-08-05",
    "explanation": "What it would look like to leave planet Earth? Such an event was recorded visually in great detail by the MESSENGER spacecraft as it swung back past the Earth, eight years ago, on its way in toward the planet Mercury. Earth can be seen rotating in this time-lapse video, as it recedes into the distance. The sunlit half of Earth is so bright that background stars are not visible. The robotic MESSENGER spacecraft is now in orbit around Mercury and has recently concluded the first complete map of the surface. On occasion, MESSENGER has continued to peer back at its home world. MESSENGER is one of the few things created on the Earth that has left and will never return -- at the end of its mission MESSENGER will be crashed into Mercury's surface.",
    "media_type": "video",
    "service_version": "v1",
    "title": "Leaving Earth",
    "url": "//www.youtube.com/embed/rFDjAfwmWKM?rel=0",
    "likes": "0"
    },
    {
    "copyright": "CfA1.2-m TelescopeWhipple Observatory",
    "date": "1998-07-19",
    "explanation": "This huge ball of stars predates our Sun. Long before mankind evolved, before dinosaurs roamed, and even before our Earth existed, ancient globs of stars condensed and orbited a young Milky Way Galaxy. Of the 250 or so globular clusters that survive today, M3 is one of the largest and brightest, easily visible in the Northern hemisphere with binoculars.  M3 contains about half a million stars, most of which are old and red. The existence of young blue stars in M3 once posed a mystery, but these blue stragglers are now thought to form via stellar interactions.",
    "hdurl": "https://apod.nasa.gov/apod/image/9612/m3_cfa_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Globular Cluster M3",
    "url": "https://apod.nasa.gov/apod/image/9612/m3_cfa.gif",
    "likes": "0"
    },
    {
    "date": "1999-10-09",
    "explanation": "Astronomers have discovered that looking at dust along the plane of our Milky Way Galaxy is a bit like looking into a frothy glass of beer. The dust between stars in our galaxy appears to be arranged like a foam with bubbles and voids -- churned by shocks and winds generated as stars cycle through their lives. This processed infrared image, based on data from NASA's IRAS satellite, maps the radiation from the edges of galactic dust clouds and reveals the complex distribution. The image covers an area of about 40x60 degrees centered on the galactic plane near the Cygnus region. It shows bright bubble-shaped and arc-like dust clouds around the supernova remnants and starbirth regions embedded in the galactic disk.",
    "hdurl": "https://apod.nasa.gov/apod/image/9910/iras_waller1_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The Frothy Milky Way",
    "url": "https://apod.nasa.gov/apod/image/9910/iras_waller1.jpg",
    "likes": "0"
    },
    {
    "copyright": "Cassini Imaging TeamISSJPLESANASAS. Van Vuuren\nMusic:\nAdagio for Strings\n(NY Philharmonic)\n",
    "date": "2020-04-19",
    "explanation": "What would it look like to approach Saturn in a spaceship? One doesn't have to just imagine -- the Cassini spacecraft did just this in 2004, recording thousands of images along the way, and hundreds of thousands more since entering orbit. Some of Cassini's early images have been digitally tweaked, cropped, and compiled into the featured inspiring video which is part of a larger developing IMAX movie project named In Saturn's Rings.  In the concluding sequence, Saturn looms increasingly large on approach as cloudy Titan swoops below. With Saturn whirling around in the background, Cassini is next depicted flying over Mimas, with large Herschel Crater clearly visible. Saturn's majestic rings then take over the show as Cassini crosses Saturn's thin ring plane. Dark shadows of the ring appear on Saturn itself. Finally, the enigmatic ice-geyser moon Enceladus appears in the distance and then is approached just as the video clip ends. After more than a decade of exploration and discovery, the Cassini spacecraft ran low on fuel in 2017 was directed to enter Saturn's atmosphere, where it surely melted.",
    "media_type": "video",
    "service_version": "v1",
    "title": "Cassini Approaches Saturn",
    "url": "https://player.vimeo.com/video/11386048#t=0m58s?color=8BA0FF&portrait=0",
    "likes": "0"
    },
    {
    "date": "2002-06-13",
    "explanation": "The Tarantula Nebula is more than 1,000 light-years across - a giant emission nebula within our neighboring galaxy the Large Magellanic Cloud. Inside this cosmic arachnid lies a central young cluster of massive stars, cataloged as R136, whose intense radiation and strong winds have helped energize the nebular glow and shape the spidery filaments. In this impressive color mosaic of images from the Wide-Field Imager camera on ESO's 2.2 meter telescope at La Silla Observatory, other young star clusters can be seen still within the nebula's grasp. Also notable among the denizens of the Tarantula zone are several dark clouds invading the nebula's outer limits as well as the dense cluster of stars NGC 2100 at the extreme left edge of the picture. The small but expanding remnant of supernova 1987a, the closest supernova in modern history, lies just off the lower right corner of the field. The rich mosaic's field of view covers an area on the sky about the size of the full moon in the southern constellation Dorado.",
    "hdurl": "https://apod.nasa.gov/apod/image/0206/tarantula_esowfi_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The Tarantula Zone",
    "url": "https://apod.nasa.gov/apod/image/0206/tarantula_esowfi.jpg",
    "likes": "0"
    },
    {
    "copyright": "Lance McVay",
    "date": "2007-11-19",
    "explanation": "Some auroras can only be seen with a camera.  They are called sub-visual and are too faint to be seen with the unaided eye.  The reason is that the human eye only accumulates light for a fraction of a second at a time, while a camera shutter can be left open indefinitely.  When photographing an already picturesque scene above Juneau, Alaska, USA, a camera caught green sub-visual aurora near the horizon.  Auroras are sparked by energetic particles from the Sun impacting the  magnetic environment around the Earth.  Resultant energetic particles such as electrons and protons rain down near the Earth's poles and impact the air.  The impacted air molecules temporarily lose electrons, and when oxygen molecules among them reacquire these electrons, they emit green light.  Auroras are known to have many shapes and colors.",
    "hdurl": "https://apod.nasa.gov/apod/image/0711/aurora_mcvay.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Aurora in the Distance",
    "url": "https://apod.nasa.gov/apod/image/0711/aurora_mcvay.jpg",
    "likes": "0"
    },
    {
    "copyright": "Tom MastersonTransient Astronomer",
    "date": "2018-02-12",
    "explanation": "What's that heading for the Pleiades star cluster? It appears to be Comet C/2016 R2 (PanSTARRS), but here, appearances are deceiving.  On the right and far in the background, the famous Pleiades star cluster is dominated by blue light from massive young stars.  On the left and visiting the inner Solar System is Comet PanSTARRS, a tumbling block of ice from the outer Solar System that currently sports a long ion tail dominated by blue light from an unusually high abundance of ionized carbon monoxide.  Comet PanSTARRS is actually moving toward the top of the image, and its ion tail points away from the Sun but is affected by a complex  solar wind of particles streaming out from the Sun.  Visible through a small telescope, the comet is fading as it recedes from the Earth, even though it reaches its closest point to the Sun in early May.",
    "hdurl": "https://apod.nasa.gov/apod/image/1802/BlueCometPleiades_Masterson_5407.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Blue Comet Meets Blue Stars",
    "url": "https://apod.nasa.gov/apod/image/1802/BlueCometPleiades_Masterson_1080.jpg",
    "likes": "0"
    },
    {
    "copyright": "Rogelio Bernal\nAndreo",
    "date": "2015-06-27",
    "explanation": "Rising at the start of a northern summer's night, these three bright stars form the familiar asterism known as the Summer Triangle. Altair, Deneb, and Vega are the alpha stars of their respective constellations, Aquila, Cygnus, and Lyra, nestled near the Milky Way. Close in apparent brightness the three do look similar in these telescopic portraits, but all have their own stellar stories. Their similar appearance hides the fact that the Summer Triangle stars actually span a large range in intrinsic luminosity and distance. A main sequence dwarf star, Altair is some 10 times brighter than the Sun and 17 light-years away, while Vega, also a hydrogen-fusing dwarf, is around 30 times brighter than the Sun and lies 25 light-years away. Supergiant Deneb, at about 54,000 times the solar luminosity, lies some 1,400 light-years distant. Of course, with a whitish blue hue, the stars of the Summer Triangle are all hotter than the Sun.",
    "hdurl": "https://apod.nasa.gov/apod/image/1506/RBA_ADV_2048.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Stars of a Summer's Triangle",
    "url": "https://apod.nasa.gov/apod/image/1506/RBA_ADV_1024.jpg",
    "likes": "0"
    },
    {
    "date": "2020-09-06",
    "explanation": "This is the mess that is left when a star explodes.  The Crab Nebula, the result of a supernova seen in 1054 AD, is filled with mysterious filaments.  The filaments are not only tremendously complex, but appear to have less mass than expelled in the original supernova and a higher speed than expected from a free explosion.  The featured image, taken by the Hubble Space Telescope, is presentedi in three colors chosen for scientific interest.  The Crab Nebula spans about 10 light-years.  In the nebula's very center lies a pulsar: a neutron star as massive as the Sun but with only the size of a small town.  The Crab Pulsar rotates about 30 times each second.",
    "hdurl": "https://apod.nasa.gov/apod/image/2009/CrabNebula_Hubble_3864.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "M1: The Crab Nebula from Hubble",
    "url": "https://apod.nasa.gov/apod/image/2009/CrabNebula_Hubble_960.jpg",
    "likes": "0"
    },
    {
    "date": "1997-02-14",
    "explanation": "Globular clusters\r once ruled the Milky Way. Back in\r the old days, back when our Galaxy\r first formed, perhaps thousands of globular clusters roamed our\r Galaxy. Today, there are perhaps 200 left.\r Many globular clusters were destroyed\r over the eons by repeated fateful encounters with each other or\r the Galactic center. Surviving relics\r are older than any earth fossil,\r older than any other structures in our Galaxy,\r and limit the universe itself\r in raw age. There are few, if any, young globular clusters\r in our Milky Way Galaxy because conditions\r are not ripe for more to form. But things are different next\r door - in the neighboring LMC galaxy.\r Pictured above is a \"young\" globular cluster residing\r there: NGC 1818.\r Recent observations show it formed only about 40 million years\r ago - just yesterday compared to the 12 billion year ages of globular clusters in our own Milky Way",
    "hdurl": "https://apod.nasa.gov/apod/image/9702/ngc1818_hst_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "NGC 1818: A Young Globular Cluster\r\nCredit:",
    "url": "https://apod.nasa.gov/apod/image/9702/ngc1818_hst.jpg",
    "likes": "0"
    },
    {
    "copyright": "Emil Ivanov",
    "date": "2012-06-08",
    "explanation": "This dramatic telephoto view across the Black Sea on June 6 finds Venus rising with the Sun, the planet in silhouette against a ruddy and ragged solar disk. Of course, the reddened light is due to scattering in planet Earth's atmosphere and the rare transit of Venus didn't influence the strangely shaped and distorted Sun. In fact, seeing the Sun in the shape of an Etruscan Vase is relatively common, especially compared to Venus transits. At sunset and sunrise, the effects of atmospheric refraction enhanced by long, low, sight lines and strong atmospheric temperature gradients produce the visual distortions and mirages. That situation is often favored by a sea horizon.",
    "hdurl": "https://apod.nasa.gov/apod/image/1206/VenusTransit2012_ivanov2b.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "When Venus Rises with the Sun",
    "url": "https://apod.nasa.gov/apod/image/1206/VenusTransit2012_ivanov2b900.jpg",
    "likes": "0"
    },
    {
    "date": "2009-12-07",
    "explanation": "This was home.  Just over a week ago, the STS-129 crew of the Space Shuttle Atlantis undocked from the International Space Station (ISS) and returned to Earth.  As the shuttle departed the space station, they took the  above image.  Visible on the ISS are numerous modules, trusses, and long wing-like solar panels.  The space shuttle crew spent almost 12 days calling the space station home.  The shuttle crew resupplied the space station and delivered valuable spare parts.  The ISS continues to be home for five astronauts of Expedition 21. The ISS's crew now includes astronauts representing NASA, the European Space Agency, the Russian Federal Space Agency, and the Canadian Space Agency.    digg_url = 'http://apod.nasa.gov/apod/ap091207.html'; digg_skin = 'compact';",
    "hdurl": "https://apod.nasa.gov/apod/image/0912/iss_sts129_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The International Space Station Over the Horizon",
    "url": "https://apod.nasa.gov/apod/image/0912/iss_sts129.jpg",
    "likes": "0"
    },
    {
    "copyright": "Celestial Visions",
    "date": "2008-09-12",
    "explanation": "A bright trio of terrestrial planets was joined by a young Moon on September 1st, in planet Earth's early evening skies. In this view of the celestial gathering from Perth, Western Australia, the Moon's sunlit crescent is nearly horizontal at Perth's southern latitude of about 32 degrees. Venus, then Mercury, and finally Mars shine above colorful city lights on the far shore of the Swan River. The six unlit towers on the left surround a large cricket stadium. For now, the planetary trio still lingers low in the west just after sunset. But in the coming days Venus will move farther from the Sun, climbing higher after sunset, while Mercury and Mars will steadily sink into the glare along the western horizon.   Note: Free Astronomy Course Taught Online by an APOD Editor  digg_url = 'http://apod.nasa.gov/apod/ap080912.html'; digg_skin = 'compact';",
    "hdurl": "https://apod.nasa.gov/apod/image/0809/planetsPerth_Goldsmith.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Planets over Perth",
    "url": "https://apod.nasa.gov/apod/image/0809/planetsPerth_Goldsmith_c800.jpg",
    "likes": "0"
    },
    {
    "copyright": "Daniel Herron",
    "date": "2017-03-17",
    "explanation": "Just as the Moon goes through phases, Venus' visible sunlit hemisphere waxes and wanes. This composite of telescopic images illustrates the steady changes for the inner planet, seen in the west as the evening star, as Venus grows larger but narrows to a thin crescent from December 20, 2016 through March 10. Gliding along its interior orbit between Earth and Sun, Venus grows larger during that period because it is approaching planet Earth. Its crescent narrows, though, as Venus swings closer to our line-of-sight to the Sun. Closest to the Earth-Sun line but passing about 8 degrees north of the Sun on March 25, Venus will reach a (non-judgmental) inferior conjunction. Soon after, Venus will shine clearly above the eastern horizon in predawn skies as planet Earth's morning star.",
    "hdurl": "https://apod.nasa.gov/apod/image/1703/VenusDec2016March2017small.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Phases of Venus",
    "url": "https://apod.nasa.gov/apod/image/1703/VenusDec2016March2017smallC.jpg",
    "likes": "0"
    },
    {
    "copyright": "Joonhwa Lee",
    "date": "2018-05-04",
    "explanation": "Big, beautiful spiral galaxy M101 is one of the last entries in Charles Messier's famous catalog, but definitely not one of the least. About 170,000 light-years across, this galaxy is enormous, almost twice the size of our own Milky Way galaxy. M101 was also one of the original spiral nebulae observed by Lord Rosse's large 19th century telescope, the Leviathan of Parsontown. M101 shares this modern telescopic field of view with spiky foreground stars within the Milky Way and a companion dwarf galaxy NGC 5474 (lower right). The colors of the Milky Way stars can also be found in the starlight from the large island universe. Its core is dominated by light from cool yellowish stars. Along its grand design spiral arms are the blue colors of hotter, young stars mixed with obscuring dust lanes and pinkish star forming regions. Also known as the Pinwheel Galaxy, M101 lies within the boundaries of the northern constellation Ursa Major, about 23 million light-years away. NGC 5474 has likely been distorted by its past gravitational interactions with the dominant M101.",
    "hdurl": "https://apod.nasa.gov/apod/image/1805/M101_3Days_New_APOD.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The View Toward M101",
    "url": "https://apod.nasa.gov/apod/image/1805/M101_3Days_New_APOD1024.jpg",
    "likes": "0"
    },
    {
    "copyright": "ALSJ",
    "date": "2008-08-10",
    "explanation": "Get out your red/blue glasses and check out this remarkable stereo view from lunar orbit. Created from two photographs (AS11-44-6633, AS11-44-6634) taken by astronaut Michael Collins during the 1969 Apollo 11 mission, the 3D anaglyph features the lunar module ascent stage, dubbed The Eagle, as it rises to meet the command module in lunar orbit. Aboard the ascent stage are Neil Armstrong and Buzz Aldrin, the first to walk on the Moon. The smooth, dark area on the lunar surface is Mare Smythii located just below the equator on the extreme eastern edge of the Moon's near side.  Poised beyond the lunar horizon, is our fair planet Earth.   digg_url = 'http://apod.nasa.gov/apod/ap080810.html'; digg_skin = 'compact';",
    "hdurl": "https://apod.nasa.gov/apod/image/0808/AS11JK44-6633-34.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "The Eagle Rises",
    "url": "https://apod.nasa.gov/apod/image/0808/AS11JK44-6633-34_c800.jpg",
    "likes":'0'
    },
    {
    "copyright": "Jingyi Zhang",
    "date": "2020-08-17",
    "explanation": "Why would meteor trails appear curved? The arcing effect arises only because the image artificially compresses (nearly) the whole sky into a rectangle. The meteors are from the Perseid Meteor Shower that peaked last week. The featured multi-frame image combines not only different directions from the 360 projection, but different times when bright Perseid meteors momentarily streaked across the sky. All Perseid meteors can be traced back to the constellation Perseus toward the lower left, even the seemingly curved (but really straight) meteor trails.  Although Perseids always point back to their Perseus radiant, they can appear almost anywhere on the sky. The image was taken from Inner Mongolia, China, where grasslands meet sand dunes. Many treasures also visible in the busy night sky including the central arch of our Milky Way Galaxy, the planets Saturn and Jupiter toward the right, colorful airglow on the central left, and some relatively nearby Earthly clouds.  The Perseid Meteor Shower peaks every August.    Perseid Meteor Shower: Notable images submitted to APOD",
    "hdurl": "https://apod.nasa.gov/apod/image/2008/PerseidBridge_Zhang_4032.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Perseids Around the Milky Way",
    "url": "https://apod.nasa.gov/apod/image/2008/PerseidBridge_Zhang_1080.jpg",
    "likes": "0"
    },
    {
    "copyright": "Emiel Kempen",
    "date": "2008-01-02",
    "explanation": "This gorgeous galaxy and comet portrait was recorded on December 30th, in the skies over Hoogeveen, The Netherlands. The combined series of 60 x 60 second exposures finds the lovely green coma of Comet 8P/Tuttle near its predicted conjunction with the Triangulum Galaxy. Aligning each exposure with the stars shows the comet as a streak, slowly moving against the background stars and galaxy. An alternative composition with exposures centered on the comet, shows the background stars and galaxy as streaks. The alluring celestial scene would also have been a rewarding one for the influential 18th century comet hunter Charles Messier. While Messier scanned French skies for comets, he carefully cataloged positions of things which were fuzzy and comet-like in appearance but did not move against the background stars and so were definitely not comets. The Triangulum Galaxy, also known as M33, is the 33rd object in his famous not-a-comet catalog. The modern understanding holds that the Triangulum Galaxy is a large spiral galaxy some 3 million light-years distant. Comet 8P/Tuttle, just bright enough to be visible to the unaided eye in dark, northern skies, is about 40 million kilometers (2 light-minutes) away.   The Amateur Astronomers Association of New York Presents: APOD Editor's Lecture: January 4th - American Museum of Natural History",
    "hdurl": "https://apod.nasa.gov/apod/image/0801/M33tuttle_kempenStar.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "A Galaxy is not a Comet",
    "url": "https://apod.nasa.gov/apod/image/0801/M33tuttle_kempenStar800.jpg",
    "likes": "0"
    },
    {
    "date": "2004-12-17",
    "explanation": "In Greek Mythology, Prometheus was known for stealing fire from the gods. Ironically, in a story for more modern times Prometheus may also become known for stealing, but this time for stealing icy particles from Saturn's rings. This eerie close-up from the Cassini spacecraft shows the 100 kilometer-long Saturnian moon Prometheus orbiting near the inner edge of Saturn's F ring. The dramatic view clearly resolves the potato-shaped moon and multiple strands of the narrow F ring. It also reveals a faint strand of material connecting Prometheus with the rings. One possibility is that the tiny moon's gravity is indeed drawing off particles from the rings and is influencing the formation of the gaps and kinks seen in the ring structure.",
    "hdurl": "https://apod.nasa.gov/apod/image/0412/prometheus_cassini_f.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Prometheus and the Rings of Saturn",
    "url": "https://apod.nasa.gov/apod/image/0412/prometheus_cassini_b.jpg",
    "likes": "0"
    },
    {
    "date": "1998-09-18",
    "explanation": "Launched on January 6th, NASA's Lunar Prospector spacecraft has been exploring the Moon with instruments designed to sense global properties while orbiting pole-to-pole, 63 miles above the lunar surface. Now over half way through its primary mission, impressive science results include a much-needed precision gravity map of the lunar surface, global maps of elemental composition, the detection of mini-magnetospheres related to large impact sites, and evidence pointing toward a small iron-rich lunar core. But perhaps the most spectacular recent announcement has underscored Prospector's earlier block-buster - the detection of substantial water-ice at both the North and South lunar poles. An analysis of data collected so far is consistent with near-pure water ice deposits - the residue of cometary impacts - buried beneath as much as 18 inches of dry dusty regolith. And the estimates now suggest 10 times more water in each polar region than previously thought! The small Prospector spacecraft carries no cameras for lunar imaging, but the Moon is relatively well photographed. This detailed, color-enhanced nearside mosaic was produced from images taken by the Galileo spacecraft as it passed the Moon in December of 1992.",
    "hdurl": "https://apod.nasa.gov/apod/image/9809/fullmoonmosaic_gal_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Lunar Prospects",
    "url": "https://apod.nasa.gov/apod/image/9809/moonmosaic1_gal.jpg",
    "likes": "0"
    },
    {
    "copyright": "Juan Carlos CasadoTWANEarth and Stars",
    "date": "2013-12-17",
    "explanation": "On some nights it rains meteors. Peaking two nights ago, asteroid dust streaked through the dark skies of Earth, showering down during the annual Geminids meteor shower. Astrophotographer Juan Carlos Casado captured the space weather event, as pictured above, in a series of exposures spanning about 2.3 hours using a wide angle lens. The snowcapped Teide volcano of the Canary Islands of Spain towers in the foreground, while the picturesque constellation of Orion highlights the background. The star appearing just near the top of the volcano is Rigel. Although the asteroid dust particles are traveling parallel to each other, the resulting meteor streaks appear to radiate from a single point on the sky, in this case in the constellation of Gemini, off the top of the image.  Like train tracks appearing to converge in the distance, the meteor radiant effect is due to perspective. The astrophotographer has estimated that there are about 50 Geminids visible in the above composite image -- how many do you see?    Budget Universe: Free APOD 2014 Calendar in PDF format",
    "hdurl": "https://apod.nasa.gov/apod/image/1312/geminds2013_jcc_1500.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Geminid Meteors over Teide Volcano",
    "url": "https://apod.nasa.gov/apod/image/1312/geminds2013_jcc_960.jpg",
    "likes": "0"
    },
    {
    "copyright": "Anglo-Australian Telescope\nBoard",
    "date": "1998-06-13",
    "explanation": "Stars with tens of times the mass of the Sun profoundly affect their galactic environment. Churning and mixing the interstellar gas and dust clouds they leave their mark in the compositions and locations of future generations of stars and star systems. Dramatic evidence of this is beautifully illustrated in our neighboring galaxy, the Large Magellanic Cloud (LMC), by the lovely ring shaped nebula, Henize 70. It is actually a luminous \"superbubble\" of interstellar gas about 300 lightyears in diameter, blown by winds from massive stars and supernova explosions, its interior filled with tenuous hot expanding gas. These superbubbles offer astronomers a chance to explore this crucial connection between the lifecycles of stars and the evolution of galaxies.",
    "hdurl": "https://apod.nasa.gov/apod/image/9806/henize70_aat.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Henize 70: A SuperBubble In The LMC",
    "url": "https://apod.nasa.gov/apod/image/9806/henize70_aat.jpg",
    "likes": "0"
    },
    {
    "date": "2000-01-06",
    "explanation": "Tomorrow's picture: Starworks  < Archive | Index | Search | Calendar | Glossary | Education | About APOD >  Authors & editors: Robert Nemiroff (MTU) & Jerry Bonnell (USRA) NASA Technical Rep.: Jay Norris. Specific rights apply. A service of: LHEA at NASA/ GSFC & Michigan Tech. U.",
    "hdurl": "https://apod.nasa.gov/apod/image/0001/marsy2k_mgs_big.gif",
    "media_type": "image",
    "service_version": "v1",
    "title": "Mars in the New Year",
    "url": "https://apod.nasa.gov/apod/image/0001/marsy2k_mgs_c1.jpg",
    "likes": "0"
    },
    {
    "date": "2018-06-03",
    "explanation": "What has happened to Saturn's moon Iapetus?  Vast sections of this strange world are dark as coal, while others are as bright as ice.  The composition of the dark material is unknown, but infrared spectra indicate that it possibly contains some dark form of carbon. Iapetus also has an unusual equatorial ridge that makes it appear like a walnut.  To help better understand this seemingly painted moon, NASA directed the robotic Cassini spacecraft orbiting Saturn to swoop within 2,000 kilometers in 2007. Pictured here, from about 75,000 kilometers out, Cassini's trajectory allowed unprecedented imaging of the hemisphere of Iapetus that is always trailing.  A huge impact crater seen in the south spans a tremendous 450 kilometers and appears superposed on an older crater of similar size. The dark material is seen increasingly coating the easternmost part of Iapetus, darkening craters and highlands alike.  Close inspection indicates that the dark coating typically faces the moon's equator and is less than a meter thick. A leading hypothesis is that the dark material is mostly dirt leftover when relatively warm but dirty ice sublimates. An initial coating of dark material may have been effectively painted on by the accretion of meteor-liberated debris from other moons.",
    "hdurl": "https://apod.nasa.gov/apod/image/1806/iapetus3_cassini_4100.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Saturn's Iapetus: Painted Moon",
    "url": "https://apod.nasa.gov/apod/image/1806/iapetus3_cassini_960.jpg",
    "likes": "0"
    },
    {
    "copyright": "Terrastro",
    "date": "2018-08-09",
    "explanation": "Mars is also known as The Red Planet, often seen with a reddish tinge in dark night skies. Mars shines brightly at the upper left of this gorgeous morning twilight view from Mornington Peninsula, Victoria, Australia, but the Moon and planet Earth look redder still. Taken on July 27, the totally eclipsed Moon is setting. It looks reddened because the Earth's umbral shadow isn't completely dark. Instead Earth's shadow is suffused with a faint red light from all the planet's sunsets and sunrises seen from the perspective of an eclipsed Moon. The sunsets and sunrises are reddened because Earth's atmosphere scatters blue light more strongly than red, creating the faint bluish twilight sky. Of course, craggy seaside rocks also take on the reddened colors of this Australian sunrise.",
    "hdurl": "https://apod.nasa.gov/apod/image/1808/Cherney_TLE201807.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Red Planet, Red Moon, and Mars",
    "url": "https://apod.nasa.gov/apod/image/1808/Cherney_TLE201807_1024.jpg",
    "likes": "0"
    },
    {
    "date": "2002-11-30",
    "explanation": "This panorama of the cratered lunar surface was constructed from images returned by the US Surveyor 6 lander. Surveyor 6 was not the first spacecraft to accomplish a soft landing on the Moon ... but it was the first to land and then lift off again! After the spacecraft touched down near the center of the Moon's nearside in November of 1967, NASA controllers commanded it to hop. Briefly firing its rocket engine and lifting itself some 4 meters above the surface, the Surveyor moved about 2.5 meters to one side before setting down again. The hopping success of Surveyor 6 essentially marked the completion of the Surveyor series main mission - to determine if the lunar terrain was safe for the planned Apollo landings.",
    "hdurl": "https://apod.nasa.gov/apod/image/0211/pan_surveyor6_full.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Surveyor Hops",
    "url": "https://apod.nasa.gov/apod/image/0211/pan_surveyor6_full.jpg",
    "likes": "0"
    },
    {
    "date": "2017-07-02",
    "explanation": "It's stars versus dust in the Carina Nebula and the stars are winning. More precisely, the energetic light and winds from massive newly formed stars are evaporating and dispersing the dusty stellar nurseries in which they formed. Located in the Carina Nebula and known informally as Mystic Mountain, these pillar's appearance is dominated by the dark dust even though it is composed mostly of clear hydrogen gas. Dust pillars such as these are actually much thinner than air and only appear as mountains due to relatively small amounts of opaque interstellar dust.  About 7,500 light-years distant, the featured image was taken with the Hubble Space Telescope and highlights an interior region of Carina which spans about three light years. Within a few million years, the stars will likely win out completely and the entire dust mountain will evaporate.",
    "hdurl": "https://apod.nasa.gov/apod/image/1707/carina08_hubble_2104.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Mountains of Dust in the Carina Nebula",
    "url": "https://apod.nasa.gov/apod/image/1707/carina08_hubble_960.jpg",
    "likes": "0"
    },
    {
    "copyright": "Jimmy WestlakeColorado\nMountain College",
    "date": "2004-06-09",
    "explanation": "Did you see the transit? While some watched by webcast, sky gazers in Europe, the Middle East, Africa, and Asia were able to witness the complete 6 hour journey of Venus' silhouetted disk across the face of the Sun. As seen from North America, the much heralded Venus Transit of 2004 was nearing its final stages at sunrise yesterday in this telescopic image. The view looks across the Atlantic from Tybee Island near Savannah, Georgia, USA. In fact, many in eastern North America experienced a dramatic view of a perfect, dark, round Venus against a reddened Sun filtered by banks of low clouds. Ironically, the Sun takes on the appearance of a cloud covered planet itself as Venus marches toward the right through this dreamlike scene.",
    "hdurl": "https://apod.nasa.gov/apod/image/0406/vt2004_westlake.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Venus Transit at Sunrise",
    "url": "https://apod.nasa.gov/apod/image/0406/vt2004_westlake_c1.jpg",
    "likes": "0"
    },
    {
    "copyright": "Jens Hackmann",
    "date": "2011-02-11",
    "explanation": "What determines a star's color? Its temperature. Red stars are cool, with surface temperatures of around 3,000 kelvins (K), while blue stars are hotter and can have temperatures over 30,000 K. Our own lovely \"yellow\" Sun's temperature is a comforting 6,000 K. Differences in star colors are particularly easy to see in this intriguing composite view of the constellation Orion, made while experimenting with a star trail step-focus technique. In it, a series of 35 consecutive exposures were combined to produce trails of stars moving left to right through the frame, while changing focus in steps. Beginning and ending with the camera out of focus produced a sharply focused exposure near the middle of the series and blurs the star trails into a bow tie shape. For the brighter stars, blurring produces more saturated colors in the images. At the upper left, Orion's cool red supergiant Betelgeuse stands out from the other, hotter, bluish stars composing the body of the constellation. Not a star at all, the Orion Nebula contributes a pinkish tint below center. Also remarkable in the field, the fainter step focus trail of cool, deep red carbon star W Orionis is near the center right edge, its red hue enhanced by a carbon-rich composition.",
    "hdurl": "https://apod.nasa.gov/apod/image/1102/OrionColors_hackmann.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Star Colors in Orion",
    "url": "https://apod.nasa.gov/apod/image/1102/OrionColors_hackmann900h.jpg",
    "likes": "0"
    },
    {
    "copyright": "T. Rector",
    "date": "2011-05-01",
    "explanation": "It may look to some like a duck, but it lays stars instead of eggs.  In the center of the above image lies Barnard 163, a nebula of molecular gas and dust so thick that visible light can't shine through it.  With a wing span measured in light years, Barnard 163's insides are surely colder than its exterior, allowing conditions where gas can clump and eventually form stars.  Barnard 163 lies about 3,000 light years from Earth toward the constellation of Cepheus the King. The red glow in the background results from IC 1396, a large emission nebula that houses the Elephant's Trunk Nebula.  Finding Barnard 163 in an image of its greater emission nebula IC 1396 can be a challenge, but it's possible.",
    "hdurl": "https://apod.nasa.gov/apod/image/1105/barnard163_wiyn_2000.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Molecular Cloud Barnard 163",
    "url": "https://apod.nasa.gov/apod/image/1105/barnard163_wiyn_900.jpg",
    "likes": "0"
    },
    {
    "date": "2019-11-29",
    "explanation": "Looping through the Jovian system in the late 1990s, the Galileo spacecraft recorded stunning views of Europa and uncovered evidence that the moon's icy surface likely hides a deep, global ocean. Galileo's Europa image data has been remastered here, using improved new calibrations to produce a color image approximating what the human eye might see. Europa's long curving fractures hint at the subsurface liquid water.  The tidal flexing the large moon experiences in its elliptical orbit around Jupiter supplies the energy to keep the ocean liquid. But more tantalizing is the possibility that even in the absence of sunlight that process could also supply the energy to support life, making Europa one of the best places to look for life beyond Earth. What kind of life could thrive in a deep, dark, subsurface ocean? Consider planet Earth's own extreme shrimp.",
    "hdurl": "https://apod.nasa.gov/apod/image/1911/PIA19048europa.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Galileo's Europa Remastered",
    "url": "https://apod.nasa.gov/apod/image/1911/PIA19048europa1024.jpg",
    "likes": "0"
    },
    {
    "date": "1998-11-02",
    "explanation": "In this tangle of quasars and galaxies lies a clue to the expansion rate of the universe.  A diffuse glow evident in the picture on the left reveals a normal elliptical galaxy.  Directly behind this galaxy lies a normal quasar. Because the quasar is directly behind the galaxy, however, the gravity of the galaxy deflects quasar light like a lens, creating four bright images of the same distant quasar.  When these images are all digitally subtracted, a distorted image of the background galaxy that hosts the quasar appears - here shown on the right in ghostly white. Each quasar image traces how the quasar looked at different times in the past, with the time between images influenced by the expansion rate of the universe itself.  Assuming dark matter in the elliptical lens galaxy traces the visible matter, this expansion rate can be characterized by a Hubble constant of Ho near 65 km/sec/Mpc, a value close to that determined by other methods.  Analysis of this image by itself sheds little light on whether the global geometry of the universe is affected by a cosmological constant.",
    "hdurl": "https://apod.nasa.gov/apod/image/9811/pg1115_hst_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "PG 1115+080 A Ghost of Lensing Past",
    "url": "https://apod.nasa.gov/apod/image/9811/pg1115_hst.jpg",
    "likes": "0"
    },
    {
    "copyright": "Yuichi Takasaka",
    "date": "2011-09-23",
    "explanation": "September's equinox arrives today at 0905 UT. As the Sun crosses the celestial equator heading south, spring begins in the southern hemisphere and autumn in the north. And though the seasonal connection is still puzzling, both spring and autumn bring an increase in geomagnetic storms. So as northern nights grow longer, the equinox also heralds the arrival of a good season for viewing aurora. Recorded earlier this month, these curtains of September's shimmering green light sprawl across a gorgeous night skyscape. In the foreground lies Hidden Lake Territorial Park near Yellowknife, Northwest Territories, Canada. Calm water reflects the aurora, with bright star trails peering through the mesmerizing sky glow. Of course, shining at altitudes of 100 kilometers or so, planet Earth's auroras are visible from space.",
    "hdurl": "https://apod.nasa.gov/apod/image/1109/C404-5244-6082AuroraTakasaka.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "September's Aurora",
    "url": "https://apod.nasa.gov/apod/image/1109/C404-5244-6082AuroraTakasaka900.jpg",
    "likes": "0"
    },
    {
    "copyright": "\n",
    "date": "1995-10-24",
    "explanation": "Pictured above is a total solar eclipse, with the Sun's corona, clearly visible surrounding the Moon.  This picture is a composite of differently exposed photos of an eclipse that occurred on July 11, 1991. Today there will be another total eclipse of the Sun, the last until March 1997.  The path of today's total eclipse will begin in the Middle East, move though southern China, and end in the Pacific Ocean south of the Marshall Islands. Those only near the path will see a partial solar eclipse. NASA keeps detailed maps of the predicted path of the eclipse.",
    "hdurl": "https://apod.nasa.gov/apod/image/eclipse_albers.gif",
    "media_type": "image",
    "service_version": "v1",
    "title": "A Total Solar Eclipse",
    "url": "https://apod.nasa.gov/apod/image/eclipse_albers.gif",
    "likes": "0"
    },
    {
    "copyright": "Robert Gendler",
    "date": "2003-09-24",
    "explanation": "The small constellation Triangulum in the northern sky harbors this magnificent face-on spiral galaxy, M33. Its popular names include the Pinwheel Galaxy or just the Triangulum Galaxy. M33's diameter spans over 50,000 light-years, making it third largest in the Local Group of galaxies after the Andromeda Galaxy (M31), and our own Milky Way. About 3 million light-years from the Milky Way, M33 lies very close to the Andromeda Galaxy and observers in these two galaxies would likely have spectacular views of each other's grand spiral star systems. As for the view from planet Earth, this sharp 27 frame mosaic of M33 nicely shows off blue star clusters and pinkish star forming regions which trace the galaxy's loosely wound spiral arms. In fact, the cavernous NGC 604 is the brightest star forming region seen here, visible along an arm arcing above and to the right of the galaxy center. Like M31, M33's population of well-measured variable stars have helped make this nearby spiral a cosmic yardstick for establishing the distance scale of the Universe.",
    "hdurl": "https://apod.nasa.gov/apod/image/0309/M33colormosaic5LL_gendler_full.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "M33: Spiral Galaxy in Triangulum",
    "url": "https://apod.nasa.gov/apod/image/0309/M33colormosaic5LL_gendler_c1.jpg",
    "likes": "0"
    },
    {
    "date": "2005-11-28",
    "explanation": "What is the geologic history of Mars?  To help find out, the robot Spirit rover explored the terrain on the way up to the top of Husband Hill and took pictures along the way.  Earth-bound team members later combined images from one camera with colors from another to create this semi-realistic vista from near the top of the rugged hill.   Many rock faces were imaged and probed along the way.  The above image captures not only a high and distant Mars inside Gusev crater, but also more of the refrigerator-sized Spirit rover than other similar vistas.  Visible technology includes a wide array of energy-absorbing solar panels, a sundial, and the circular high gain communications antenna.",
    "hdurl": "https://apod.nasa.gov/apod/image/0511/husbandhill_av3_spirit_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "Vista Inside Gusev Crater on Mars",
    "url": "https://apod.nasa.gov/apod/image/0511/husbandhill_av3_spirit.jpg",
    "likes": "0"
    },
    {
    "date": "2001-06-24",
    "explanation": "It's the dim star, not the bright one, near the center of NGC 3132 that created this odd but beautiful planetary nebula.  Nicknamed the Eight-Burst Nebula and the Southern Ring Nebula, the glowing gas originated in the outer layers of a star like our Sun.  In this representative color picture, the hot blue pool of light seen surrounding this  binary system is energized by the hot surface of the faint star.  Although photographed to explore unusual symmetries, it's the asymmetries that help make this planetary nebula so intriguing.  Neither the unusual shape of the surrounding cooler shell nor the structure and placements of the cool filamentary dust lanes running across NGC 3132 are well understood.",
    "hdurl": "https://apod.nasa.gov/apod/image/0106/ngc3132_hst_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "NGC 3132: The Eight Burst Nebula",
    "url": "https://apod.nasa.gov/apod/image/0106/ngc3132_hst.jpg",
    "likes": "0"
    },
    {
    "date": "2004-01-11",
    "explanation": "Like a butterfly, a white dwarf star begins its life by casting off a cocoon that enclosed its former self.  In this analogy, however, the Sun would be a caterpillar and the ejected shell of gas would become the prettiest of all! The above cocoon, the planetary nebula designated NGC 2440,  contains one of the hottest white dwarf stars known. The white dwarf can be seen as the bright dot near the photo's center.  Our Sun will eventually become a \"white dwarf butterfly\", but not for another 5 billion years.  The above false color image was post-processed by Forrest Hamilton.",
    "hdurl": "https://apod.nasa.gov/apod/image/0108/ngc2440_hst4_big.jpg",
    "media_type": "image",
    "service_version": "v1",
    "title": "NGC 2440: Cocoon of a New White Dwarf",
    "url": "https://apod.nasa.gov/apod/image/0108/ngc2440_hst4.jpg",
    "likes": "0"
    }
    ];

export default data;